"""
CodeQL 验证辅助函数
"""

import os
import re
import shutil
from pathlib import Path
from typing import Dict, Optional, Tuple


_AUTOGENERATED_PACK_MARKERS = (
    "version: 0.0.1",
    "dependencies:",
    "codeql/cpp-all",
    "extractor: cpp",
)

_LOCAL_PACK_CACHE_ROOT = Path.home() / ".codeql" / "packages"


def ensure_codeql_pack(
    query_path: str,
    codeql_path: Optional[str] = None,
    timeout: int = 300,
    search_path: Optional[str] = None,
) -> Tuple[Path, Optional[str]]:
    """为查询准备稳定的工作目录。

    当前优先使用 CodeQL distribution 自带的 search-path 解析标准库。
    对临时查询目录，如果缺少 qlpack.yml，则自动补一个离线可编译的最小 pack，
    避免把 pack 准备职责泄漏给生成智能体。
    """
    query_file = Path(query_path).resolve()
    pack_dir = query_file.parent
    pack_file = pack_dir / "qlpack.yml"
    local_cpp_version = resolve_local_codeql_pack_version("codeql/cpp-all")

    resolved_search_path = resolve_codeql_search_path(codeql_path, search_path)
    if pack_file.exists() and not _is_autogenerated_query_pack(pack_file):
        return pack_dir, None

    if not resolved_search_path:
        return pack_dir, "无法解析可用的 CodeQL search-path，且查询目录没有现成 qlpack.yml"

    try:
        _write_autogenerated_query_pack(pack_file, query_file, local_cpp_version)
    except OSError as exc:
        return pack_dir, f"无法创建自动生成的 qlpack.yml: {exc}"

    return pack_dir, None


def resolve_codeql_search_path(
    codeql_path: Optional[str] = None,
    configured_search_path: Optional[str] = None,
) -> Optional[str]:
    """解析可用于离线编译/运行查询的 CodeQL search-path。"""
    configured = str(configured_search_path or "").strip()
    if configured:
        candidate = Path(configured).expanduser().resolve()
        if candidate.exists():
            return str(candidate)

    distribution_root = _infer_codeql_distribution_root(codeql_path)
    if distribution_root is not None:
        return str(distribution_root)
    return None


def build_codeql_search_path_args(
    codeql_path: Optional[str] = None,
    configured_search_path: Optional[str] = None,
) -> list[str]:
    """构建 CodeQL 命令行的 search-path 参数。"""
    args: list[str] = []
    resolved = resolve_codeql_search_path(codeql_path, configured_search_path)
    if resolved:
        args.append(f"--search-path={resolved}")

    additional = resolve_codeql_additional_packs_path()
    if additional:
        args.append(f"--additional-packs={additional}")
    return args


def _infer_codeql_distribution_root(codeql_path: Optional[str]) -> Optional[Path]:
    raw_path = str(codeql_path or "").strip()
    resolved: Optional[Path] = None

    if raw_path:
        candidate = Path(raw_path).expanduser()
        if candidate.exists():
            resolved = candidate.resolve()
        else:
            located = shutil.which(raw_path)
            if located:
                resolved = Path(located).resolve()

    if resolved is None:
        located = shutil.which("codeql")
        if located:
            resolved = Path(located).resolve()

    if resolved is None:
        return None

    distribution_root = resolved.parent
    if (distribution_root / "cpp").exists():
        return distribution_root
    return None


def _is_autogenerated_query_pack(pack_file: Path) -> bool:
    try:
        content = pack_file.read_text(encoding="utf-8")
    except OSError:
        return False

    if "name: custom-queries-" not in content:
        return False
    return all(marker in content for marker in _AUTOGENERATED_PACK_MARKERS)


def _write_autogenerated_query_pack(pack_file: Path, query_file: Path, cpp_all_version: Optional[str]) -> None:
    query_stem = re.sub(r"[^0-9A-Za-z]+", "-", query_file.stem).strip("-").lower() or "query"
    dependency_version = str(cpp_all_version or "*").strip() or "*"
    content = (
        f"name: custom-queries-{query_stem}\n"
        "version: 0.0.1\n"
        "dependencies:\n"
        f"  codeql/cpp-all: {dependency_version}\n"
        "extractor: cpp\n"
    )
    pack_file.write_text(content, encoding="utf-8")


def resolve_local_codeql_pack_version(pack_name: str) -> Optional[str]:
    namespace, _, short_name = str(pack_name or "").partition("/")
    if not namespace or not short_name:
        return None

    pack_root = _LOCAL_PACK_CACHE_ROOT / namespace / short_name
    if not pack_root.is_dir():
        return None

    versions = [child.name for child in pack_root.iterdir() if child.is_dir()]
    if not versions:
        return None
    return max(versions, key=_version_sort_key)


def resolve_codeql_additional_packs_path() -> Optional[str]:
    if not _LOCAL_PACK_CACHE_ROOT.is_dir():
        return None

    latest_dirs = []
    for packs in _collect_latest_local_pack_versions().values():
        for source_dir in packs.values():
            latest_dirs.append(str(source_dir.resolve()))
    if not latest_dirs:
        return None
    return os.pathsep.join(sorted(latest_dirs))


def _collect_latest_local_pack_versions() -> Dict[str, Dict[str, Path]]:
    latest_map: Dict[str, Dict[str, Path]] = {}
    for namespace_dir in _LOCAL_PACK_CACHE_ROOT.iterdir():
        if not namespace_dir.is_dir():
            continue
        for pack_dir in namespace_dir.iterdir():
            if not pack_dir.is_dir():
                continue
            versions = [child for child in pack_dir.iterdir() if child.is_dir()]
            if not versions:
                continue
            latest = max(versions, key=lambda path: _version_sort_key(path.name))
            latest_map.setdefault(namespace_dir.name, {})[pack_dir.name] = latest
    return latest_map


def _version_sort_key(raw: str) -> Tuple[int, ...]:
    parts = [int(token) for token in re.findall(r"\d+", str(raw or ""))]
    return tuple(parts or [0])


def is_codeql_database_dir(database_path: str) -> bool:
    """判断给定目录是否为有效的 CodeQL 数据库目录。"""
    if not database_path:
        return False

    path = Path(database_path).expanduser().resolve()
    return (
        path.is_dir()
        and (path / "codeql-database.yml").exists()
        and any(child.is_dir() and child.name.startswith("db-") for child in path.iterdir())
    )


def resolve_codeql_database_path(
    database_path: str,
    target_path: Optional[str] = None,
) -> Tuple[str, Optional[str]]:
    """解析数据库路径。"""
    if not database_path:
        return database_path, "未提供 CodeQL 数据库路径"

    candidate = Path(database_path).expanduser().resolve()
    if is_codeql_database_dir(str(candidate)):
        return str(candidate), None

    if candidate.is_dir():
        child_databases = [
            child for child in sorted(candidate.iterdir())
            if child.is_dir() and is_codeql_database_dir(str(child))
        ]

        if not child_databases:
            return str(candidate), None

        if target_path:
            target_name = Path(target_path).expanduser().resolve().stem.lower()
            for child in child_databases:
                child_name = child.name.lower()
                if target_name and (target_name in child_name or child_name in target_name):
                    return str(child), None

        if len(child_databases) == 1:
            return str(child_databases[0]), None

        return str(child_databases[0]), f"检测到多个 CodeQL 数据库，默认使用: {child_databases[0].name}"

    return str(candidate), None


def build_codeql_database_path(database_path: str, target_path: str) -> str:
    """根据配置路径和目标路径推导具体数据库目录。"""
    candidate = Path(database_path).expanduser().resolve()
    if candidate.exists() and is_codeql_database_dir(str(candidate)):
        return str(candidate)

    safe_name = re.sub(r"[^0-9A-Za-z_]+", "_", Path(target_path).expanduser().resolve().stem).strip("_")
    safe_name = safe_name or "default"

    if candidate.exists() and candidate.is_dir() and not (candidate / "codeql-database.yml").exists():
        return str((candidate / f"{safe_name}_cpp").resolve())

    return str(candidate)
