from pathlib import Path

from src.validation import codeql_support


def test_existing_archived_pack_is_preserved(tmp_path: Path) -> None:
    query = tmp_path / "archived.ql"
    query.write_text("import cpp\nselect 1\n", encoding="utf-8")
    pack = tmp_path / "qlpack.yml"
    original = (
        "name: custom-queries-probe-lines\n"
        "version: 0.0.1\n"
        "dependencies:\n"
        "  codeql/cpp-all: 8.0.3\n"
        "extractor: cpp\n"
    )
    pack.write_text(original, encoding="utf-8")

    directory, error = codeql_support.ensure_codeql_pack(str(query))

    assert directory == tmp_path
    assert error is None
    assert pack.read_text(encoding="utf-8") == original


def test_legacy_unquoted_wildcard_is_repaired(tmp_path: Path, monkeypatch) -> None:
    query = tmp_path / "legacy.ql"
    query.write_text("import cpp\nselect 1\n", encoding="utf-8")
    pack = tmp_path / "qlpack.yml"
    pack.write_text(
        "name: custom-queries-legacy\nversion: 0.0.1\n"
        "dependencies:\n  codeql/cpp-all: *\nextractor: cpp\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(codeql_support, "resolve_codeql_search_path", lambda *_: str(tmp_path))
    monkeypatch.setattr(codeql_support, "resolve_local_codeql_pack_version", lambda *_: None)

    directory, error = codeql_support.ensure_codeql_pack(str(query))

    assert directory == tmp_path
    assert error is None
    assert 'codeql/cpp-all: "*"' in pack.read_text(encoding="utf-8")
    assert codeql_support._AUTOGENERATED_PACK_MARKER in pack.read_text(encoding="utf-8")
